name: flutter_ddshare
description: A DingTalk(钉钉) flutter plugin project.Developers can use ddsharesdk easily, such as sharing text ,webpage,image and auth request.
version: 1.0.1
homepage: https://github.com/Konoha-orz/flutter_ddshare

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nbyjy.flutter_ddshare
        pluginClass: FlutterDdsharePlugin
      ios:
        pluginClass: FlutterDdsharePlugin